//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.HttpJob.Content.resx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hangfire.HttpJob.Content.resx.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 CronGenerator 的本地化字符串。
        /// </summary>
        public static string AddCronButtonName {
            get {
                return ResourceManager.GetString("AddCronButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddDelayJob 的本地化字符串。
        /// </summary>
        public static string AddHttpJobButtonName {
            get {
                return ResourceManager.GetString("AddHttpJobButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddRecurringJob 的本地化字符串。
        /// </summary>
        public static string AddRecurringJobHttpJobButtonName {
            get {
                return ResourceManager.GetString("AddRecurringJobHttpJobButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AgentJobDetail 的本地化字符串。
        /// </summary>
        public static string AgentJobDeatilButton {
            get {
                return ResourceManager.GetString("AgentJobDeatilButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CallbackEL Excute Error 的本地化字符串。
        /// </summary>
        public static string CallbackELExcuteError {
            get {
                return ResourceManager.GetString("CallbackELExcuteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CallbackEL Excute Result 的本地化字符串。
        /// </summary>
        public static string CallbackELExcuteResult {
            get {
                return ResourceManager.GetString("CallbackELExcuteResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Callback Fail 的本地化字符串。
        /// </summary>
        public static string CallbackFail {
            get {
                return ResourceManager.GetString("CallbackFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Callback Start 的本地化字符串。
        /// </summary>
        public static string CallbackStart {
            get {
                return ResourceManager.GetString("CallbackStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Callback Success 的本地化字符串。
        /// </summary>
        public static string CallbackSuccess {
            get {
                return ResourceManager.GetString("CallbackSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (choose one or many) 的本地化字符串。
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string CloseButtonName {
            get {
                return ResourceManager.GetString("CloseButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cron 的本地化字符串。
        /// </summary>
        public static string CronResult {
            get {
                return ResourceManager.GetString("CronResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JobWS 的本地化字符串。
        /// </summary>
        public static string DashboardName {
            get {
                return ResourceManager.GetString("DashboardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JobManager 的本地化字符串。
        /// </summary>
        public static string DashboardTitle {
            get {
                return ResourceManager.GetString("DashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nearest weekday (Monday to Friday) to the 的本地化字符串。
        /// </summary>
        public static string DayA {
            get {
                return ResourceManager.GetString("DayA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 st of the month 的本地化字符串。
        /// </summary>
        public static string DayB {
            get {
                return ResourceManager.GetString("DayB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Days 的本地化字符串。
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 day(s) 的本地化字符串。
        /// </summary>
        public static string Dayss {
            get {
                return ResourceManager.GetString("Dayss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DESCRIBE EXPRESSION 的本地化字符串。
        /// </summary>
        public static string DESCRIBEEXPRESSION {
            get {
                return ResourceManager.GetString("DESCRIBEEXPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HttpJob-Detail 的本地化字符串。
        /// </summary>
        public static string DingTalkConfig {
            get {
                return ResourceManager.GetString("DingTalkConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JobLogDetail 的本地化字符串。
        /// </summary>
        public static string DingTalkLogDetail {
            get {
                return ResourceManager.GetString("DingTalkLogDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RequestUrl 的本地化字符串。
        /// </summary>
        public static string DingTalkRequestUrl {
            get {
                return ResourceManager.GetString("DingTalkRequestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Response 的本地化字符串。
        /// </summary>
        public static string DingTalkResponse {
            get {
                return ResourceManager.GetString("DingTalkResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HttpJob-Alert 的本地化字符串。
        /// </summary>
        public static string DingTalkTitle {
            get {
                return ResourceManager.GetString("DingTalkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EditRecurringJob 的本地化字符串。
        /// </summary>
        public static string EditRecurringJobButtonName {
            get {
                return ResourceManager.GetString("EditRecurringJobButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every 的本地化字符串。
        /// </summary>
        public static string Every {
            get {
                return ResourceManager.GetString("Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every day 的本地化字符串。
        /// </summary>
        public static string EveryDay {
            get {
                return ResourceManager.GetString("EveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every day between 的本地化字符串。
        /// </summary>
        public static string EveryDayBetweenDay {
            get {
                return ResourceManager.GetString("EveryDayBetweenDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every hour 的本地化字符串。
        /// </summary>
        public static string EveryHour {
            get {
                return ResourceManager.GetString("EveryHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every hour between hour 的本地化字符串。
        /// </summary>
        public static string EveryHourBetweenHour {
            get {
                return ResourceManager.GetString("EveryHourBetweenHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every minute 的本地化字符串。
        /// </summary>
        public static string EveryMinute {
            get {
                return ResourceManager.GetString("EveryMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every minute between minute 的本地化字符串。
        /// </summary>
        public static string EveryMinuteBetweenMinute {
            get {
                return ResourceManager.GetString("EveryMinuteBetweenMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every month 的本地化字符串。
        /// </summary>
        public static string EveryMonth {
            get {
                return ResourceManager.GetString("EveryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every month between 的本地化字符串。
        /// </summary>
        public static string EveryMonthBetweenMonth {
            get {
                return ResourceManager.GetString("EveryMonthBetweenMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every weekday 的本地化字符串。
        /// </summary>
        public static string EveryWeekday {
            get {
                return ResourceManager.GetString("EveryWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every weekday between 的本地化字符串。
        /// </summary>
        public static string EveryWeekdayBetweenWeekday {
            get {
                return ResourceManager.GetString("EveryWeekdayBetweenWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExportJobs 的本地化字符串。
        /// </summary>
        public static string ExportJobsButtonName {
            get {
                return ResourceManager.GetString("ExportJobsButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From 的本地化字符串。
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GlobalConfig 的本地化字符串。
        /// </summary>
        public static string GobalSettingButtonName {
            get {
                return ResourceManager.GetString("GobalSettingButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hours 的本地化字符串。
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 hour(s) 的本地化字符串。
        /// </summary>
        public static string Hourss {
            get {
                return ResourceManager.GetString("Hourss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImportJobs 的本地化字符串。
        /// </summary>
        public static string ImportJobsButtonName {
            get {
                return ResourceManager.GetString("ImportJobsButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JobEnd 的本地化字符串。
        /// </summary>
        public static string JobEnd {
            get {
                return ResourceManager.GetString("JobEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JobName 的本地化字符串。
        /// </summary>
        public static string JobName {
            get {
                return ResourceManager.GetString("JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JobParam 的本地化字符串。
        /// </summary>
        public static string JobParam {
            get {
                return ResourceManager.GetString("JobParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JobResult 的本地化字符串。
        /// </summary>
        public static string JobResult {
            get {
                return ResourceManager.GetString("JobResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job Start Time 的本地化字符串。
        /// </summary>
        public static string JobStart {
            get {
                return ResourceManager.GetString("JobStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On the last day of the month 的本地化字符串。
        /// </summary>
        public static string LastDayOfMonth {
            get {
                return ResourceManager.GetString("LastDayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On the last weekday of the month 的本地化字符串。
        /// </summary>
        public static string LastWeedDayOfMonth {
            get {
                return ResourceManager.GetString("LastWeedDayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On the last weekday of the month 的本地化字符串。
        /// </summary>
        public static string LastWeekdayOfMonth {
            get {
                return ResourceManager.GetString("LastWeekdayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error retry limit reached 的本地化字符串。
        /// </summary>
        public static string LimitReached {
            get {
                return ResourceManager.GetString("LimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string LogOutButtonName {
            get {
                return ResourceManager.GetString("LogOutButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minutes 的本地化字符串。
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minute(s) 的本地化字符串。
        /// </summary>
        public static string Minutess {
            get {
                return ResourceManager.GetString("Minutess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Months 的本地化字符串。
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 month(s) 的本地化字符串。
        /// </summary>
        public static string Monthss {
            get {
                return ResourceManager.GetString("Monthss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ContinueJob Can‘t Start, Please Delete Or Retry this job!  的本地化字符串。
        /// </summary>
        public static string MultiBackgroundJobFailToContinue {
            get {
                return ResourceManager.GetString("MultiBackgroundJobFailToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NoSpecific 的本地化字符串。
        /// </summary>
        public static string NoSpecific {
            get {
                return ResourceManager.GetString("NoSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause|Start 的本地化字符串。
        /// </summary>
        public static string PauseJobButtonName {
            get {
                return ResourceManager.GetString("PauseJobButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QueuenName 的本地化字符串。
        /// </summary>
        public static string QueuenName {
            get {
                return ResourceManager.GetString("QueuenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace PlaceHolder 的本地化字符串。
        /// </summary>
        public static string ReplacePlaceHolder {
            get {
                return ResourceManager.GetString("ReplacePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HttpStatusCode 的本地化字符串。
        /// </summary>
        public static string ResponseCode {
            get {
                return ResourceManager.GetString("ResponseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pelese Enter JobName Or Args ... 的本地化字符串。
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specific 的本地化字符串。
        /// </summary>
        public static string Specific {
            get {
                return ResourceManager.GetString("Specific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specific 的本地化字符串。
        /// </summary>
        public static string SpecificMinute {
            get {
                return ResourceManager.GetString("SpecificMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartWithParam 的本地化字符串。
        /// </summary>
        public static string StartBackgroudJobButtonName {
            get {
                return ResourceManager.GetString("StartBackgroudJobButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting on the 的本地化字符串。
        /// </summary>
        public static string StartingAtDay {
            get {
                return ResourceManager.GetString("StartingAtDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every 的本地化字符串。
        /// </summary>
        public static string StartingAtDay2 {
            get {
                return ResourceManager.GetString("StartingAtDay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting at hour 的本地化字符串。
        /// </summary>
        public static string StartingAtHour {
            get {
                return ResourceManager.GetString("StartingAtHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every 的本地化字符串。
        /// </summary>
        public static string StartingAtHour2 {
            get {
                return ResourceManager.GetString("StartingAtHour2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting at minute 的本地化字符串。
        /// </summary>
        public static string StartingAtMinute {
            get {
                return ResourceManager.GetString("StartingAtMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every 的本地化字符串。
        /// </summary>
        public static string StartingAtMinute2 {
            get {
                return ResourceManager.GetString("StartingAtMinute2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting on the 的本地化字符串。
        /// </summary>
        public static string StartingAtMonth {
            get {
                return ResourceManager.GetString("StartingAtMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every 的本地化字符串。
        /// </summary>
        public static string StartingAtMontn2 {
            get {
                return ResourceManager.GetString("StartingAtMontn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StopAgent 的本地化字符串。
        /// </summary>
        public static string StopBackgroudJobButtonName {
            get {
                return ResourceManager.GetString("StopBackgroudJobButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        public static string SubmitButtonName {
            get {
                return ResourceManager.GetString("SubmitButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weekday 的本地化字符串。
        /// </summary>
        public static string Weekday {
            get {
                return ResourceManager.GetString("Weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting on the 的本地化字符串。
        /// </summary>
        public static string WeekDay1 {
            get {
                return ResourceManager.GetString("WeekDay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 st weekday  Specific day of  的本地化字符串。
        /// </summary>
        public static string WeekDay12 {
            get {
                return ResourceManager.GetString("WeekDay12", resourceCulture);
            }
        }
    }
}
