//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.HttpJob.Content.resx {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hangfire.HttpJob.Content.resx.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 CronGenerator 的當地語系化字串。
        /// </summary>
        public static string AddCronButtonName {
            get {
                return ResourceManager.GetString("AddCronButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AddDelayJob 的當地語系化字串。
        /// </summary>
        public static string AddHttpJobButtonName {
            get {
                return ResourceManager.GetString("AddHttpJobButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AddRecurringJob 的當地語系化字串。
        /// </summary>
        public static string AddRecurringJobHttpJobButtonName {
            get {
                return ResourceManager.GetString("AddRecurringJobHttpJobButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 JobCount 的當地語系化字串。
        /// </summary>
        public static string AgentJobCount {
            get {
                return ResourceManager.GetString("AgentJobCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AgentDetail 的當地語系化字串。
        /// </summary>
        public static string AgentJobDeatilButton {
            get {
                return ResourceManager.GetString("AgentJobDeatilButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure to get JobDetail? 的當地語系化字串。
        /// </summary>
        public static string AgentJobRunDetailButton {
            get {
                return ResourceManager.GetString("AgentJobRunDetailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure want to start? 的當地語系化字串。
        /// </summary>
        public static string AgentJobRunningButton {
            get {
                return ResourceManager.GetString("AgentJobRunningButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start Job Param 的當地語系化字串。
        /// </summary>
        public static string AgentJobRunningParam {
            get {
                return ResourceManager.GetString("AgentJobRunningParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start Job Success 的當地語系化字串。
        /// </summary>
        public static string AgentJobRunningSuccess {
            get {
                return ResourceManager.GetString("AgentJobRunningSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Server 的當地語系化字串。
        /// </summary>
        public static string AgentServer {
            get {
                return ResourceManager.GetString("AgentServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Heartbeat 的當地語系化字串。
        /// </summary>
        public static string AgentServerBeat {
            get {
                return ResourceManager.GetString("AgentServerBeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CallbackEL Excute Error 的當地語系化字串。
        /// </summary>
        public static string CallbackELExcuteError {
            get {
                return ResourceManager.GetString("CallbackELExcuteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CallbackEL Excute Result 的當地語系化字串。
        /// </summary>
        public static string CallbackELExcuteResult {
            get {
                return ResourceManager.GetString("CallbackELExcuteResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Callback Fail 的當地語系化字串。
        /// </summary>
        public static string CallbackFail {
            get {
                return ResourceManager.GetString("CallbackFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Callback Start 的當地語系化字串。
        /// </summary>
        public static string CallbackStart {
            get {
                return ResourceManager.GetString("CallbackStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Callback Success 的當地語系化字串。
        /// </summary>
        public static string CallbackSuccess {
            get {
                return ResourceManager.GetString("CallbackSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        public static string CancelButtonName {
            get {
                return ResourceManager.GetString("CancelButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (choose one or many) 的當地語系化字串。
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Close 的當地語系化字串。
        /// </summary>
        public static string CloseButtonName {
            get {
                return ResourceManager.GetString("CloseButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cron 的當地語系化字串。
        /// </summary>
        public static string CronResult {
            get {
                return ResourceManager.GetString("CronResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 JobWS 的當地語系化字串。
        /// </summary>
        public static string DashboardName {
            get {
                return ResourceManager.GetString("DashboardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 JobManager 的當地語系化字串。
        /// </summary>
        public static string DashboardTitle {
            get {
                return ResourceManager.GetString("DashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Nearest weekday (Monday to Friday) to the 的當地語系化字串。
        /// </summary>
        public static string DayA {
            get {
                return ResourceManager.GetString("DayA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 st of the month 的當地語系化字串。
        /// </summary>
        public static string DayB {
            get {
                return ResourceManager.GetString("DayB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Days 的當地語系化字串。
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 day(s) 的當地語系化字串。
        /// </summary>
        public static string Dayss {
            get {
                return ResourceManager.GetString("Dayss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DESCRIBE EXPRESSION 的當地語系化字串。
        /// </summary>
        public static string DESCRIBEEXPRESSION {
            get {
                return ResourceManager.GetString("DESCRIBEEXPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 HttpJob-Detail 的當地語系化字串。
        /// </summary>
        public static string DingTalkConfig {
            get {
                return ResourceManager.GetString("DingTalkConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 JobLogDetail 的當地語系化字串。
        /// </summary>
        public static string DingTalkLogDetail {
            get {
                return ResourceManager.GetString("DingTalkLogDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 RequestUrl 的當地語系化字串。
        /// </summary>
        public static string DingTalkRequestUrl {
            get {
                return ResourceManager.GetString("DingTalkRequestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Response 的當地語系化字串。
        /// </summary>
        public static string DingTalkResponse {
            get {
                return ResourceManager.GetString("DingTalkResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 HttpJob-Alert 的當地語系化字串。
        /// </summary>
        public static string DingTalkTitle {
            get {
                return ResourceManager.GetString("DingTalkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EditRecurringJob 的當地語系化字串。
        /// </summary>
        public static string EditRecurringJobButtonName {
            get {
                return ResourceManager.GetString("EditRecurringJobButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Every 的當地語系化字串。
        /// </summary>
        public static string Every {
            get {
                return ResourceManager.GetString("Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Every day 的當地語系化字串。
        /// </summary>
        public static string EveryDay {
            get {
                return ResourceManager.GetString("EveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Every day between 的當地語系化字串。
        /// </summary>
        public static string EveryDayBetweenDay {
            get {
                return ResourceManager.GetString("EveryDayBetweenDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Every hour 的當地語系化字串。
        /// </summary>
        public static string EveryHour {
            get {
                return ResourceManager.GetString("EveryHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Every hour between hour 的當地語系化字串。
        /// </summary>
        public static string EveryHourBetweenHour {
            get {
                return ResourceManager.GetString("EveryHourBetweenHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Every minute 的當地語系化字串。
        /// </summary>
        public static string EveryMinute {
            get {
                return ResourceManager.GetString("EveryMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Every minute between minute 的當地語系化字串。
        /// </summary>
        public static string EveryMinuteBetweenMinute {
            get {
                return ResourceManager.GetString("EveryMinuteBetweenMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Every month 的當地語系化字串。
        /// </summary>
        public static string EveryMonth {
            get {
                return ResourceManager.GetString("EveryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Every month between 的當地語系化字串。
        /// </summary>
        public static string EveryMonthBetweenMonth {
            get {
                return ResourceManager.GetString("EveryMonthBetweenMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Every weekday 的當地語系化字串。
        /// </summary>
        public static string EveryWeekday {
            get {
                return ResourceManager.GetString("EveryWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Every weekday between 的當地語系化字串。
        /// </summary>
        public static string EveryWeekdayBetweenWeekday {
            get {
                return ResourceManager.GetString("EveryWeekdayBetweenWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ExportJobs 的當地語系化字串。
        /// </summary>
        public static string ExportJobsButtonName {
            get {
                return ResourceManager.GetString("ExportJobsButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 From 的當地語系化字串。
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GlobalConfig 的當地語系化字串。
        /// </summary>
        public static string GobalSettingButtonName {
            get {
                return ResourceManager.GetString("GobalSettingButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hours 的當地語系化字串。
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 hour(s) 的當地語系化字串。
        /// </summary>
        public static string Hourss {
            get {
                return ResourceManager.GetString("Hourss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ImportJobs 的當地語系化字串。
        /// </summary>
        public static string ImportJobsButtonName {
            get {
                return ResourceManager.GetString("ImportJobsButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 JobEnd 的當地語系化字串。
        /// </summary>
        public static string JobEnd {
            get {
                return ResourceManager.GetString("JobEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 JobName 的當地語系化字串。
        /// </summary>
        public static string JobName {
            get {
                return ResourceManager.GetString("JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 JobParam 的當地語系化字串。
        /// </summary>
        public static string JobParam {
            get {
                return ResourceManager.GetString("JobParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 JobResult 的當地語系化字串。
        /// </summary>
        public static string JobResult {
            get {
                return ResourceManager.GetString("JobResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Job Start Time 的當地語系化字串。
        /// </summary>
        public static string JobStart {
            get {
                return ResourceManager.GetString("JobStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 On the last day of the month 的當地語系化字串。
        /// </summary>
        public static string LastDayOfMonth {
            get {
                return ResourceManager.GetString("LastDayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 On the last weekday of the month 的當地語系化字串。
        /// </summary>
        public static string LastWeedDayOfMonth {
            get {
                return ResourceManager.GetString("LastWeedDayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 On the last weekday of the month 的當地語系化字串。
        /// </summary>
        public static string LastWeekdayOfMonth {
            get {
                return ResourceManager.GetString("LastWeekdayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error retry limit reached 的當地語系化字串。
        /// </summary>
        public static string LimitReached {
            get {
                return ResourceManager.GetString("LimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Back 的當地語系化字串。
        /// </summary>
        public static string LogOutButtonName {
            get {
                return ResourceManager.GetString("LogOutButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Minutes 的當地語系化字串。
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 minute(s) 的當地語系化字串。
        /// </summary>
        public static string Minutess {
            get {
                return ResourceManager.GetString("Minutess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Months 的當地語系化字串。
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 month(s) 的當地語系化字串。
        /// </summary>
        public static string Monthss {
            get {
                return ResourceManager.GetString("Monthss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The ContinueJob Can‘t Start, Please Delete Or Retry this job!  的當地語系化字串。
        /// </summary>
        public static string MultiBackgroundJobFailToContinue {
            get {
                return ResourceManager.GetString("MultiBackgroundJobFailToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NoSpecific 的當地語系化字串。
        /// </summary>
        public static string NoSpecific {
            get {
                return ResourceManager.GetString("NoSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pause|Start 的當地語系化字串。
        /// </summary>
        public static string PauseJobButtonName {
            get {
                return ResourceManager.GetString("PauseJobButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 QueuenName 的當地語系化字串。
        /// </summary>
        public static string QueuenName {
            get {
                return ResourceManager.GetString("QueuenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Selected Job is not a jobAgent! 的當地語系化字串。
        /// </summary>
        public static string Remind_SelectNoJobAgent {
            get {
                return ResourceManager.GetString("Remind_SelectNoJobAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please Choose One Job 的當地語系化字串。
        /// </summary>
        public static string Remind_SelectOneJob {
            get {
                return ResourceManager.GetString("Remind_SelectOneJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start Job 的當地語系化字串。
        /// </summary>
        public static string Remind_StartJob {
            get {
                return ResourceManager.GetString("Remind_StartJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure want to stop? 的當地語系化字串。
        /// </summary>
        public static string Remind_StopBackgroundJob {
            get {
                return ResourceManager.GetString("Remind_StopBackgroundJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 JobAgent 的當地語系化字串。
        /// </summary>
        public static string Remind_Warning {
            get {
                return ResourceManager.GetString("Remind_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Replace PlaceHolder 的當地語系化字串。
        /// </summary>
        public static string ReplacePlaceHolder {
            get {
                return ResourceManager.GetString("ReplacePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 HttpStatusCode 的當地語系化字串。
        /// </summary>
        public static string ResponseCode {
            get {
                return ResourceManager.GetString("ResponseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pelese Enter JobName Or Args ... 的當地語系化字串。
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 use 【name:xxx】 to search jobDetail 的當地語系化字串。
        /// </summary>
        public static string SearchPlaceholderUseName {
            get {
                return ResourceManager.GetString("SearchPlaceholderUseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Specific 的當地語系化字串。
        /// </summary>
        public static string Specific {
            get {
                return ResourceManager.GetString("Specific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Specific 的當地語系化字串。
        /// </summary>
        public static string SpecificMinute {
            get {
                return ResourceManager.GetString("SpecificMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start 的當地語系化字串。
        /// </summary>
        public static string StartBackgroudJobButtonName {
            get {
                return ResourceManager.GetString("StartBackgroudJobButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Starting on the 的當地語系化字串。
        /// </summary>
        public static string StartingAtDay {
            get {
                return ResourceManager.GetString("StartingAtDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Every 的當地語系化字串。
        /// </summary>
        public static string StartingAtDay2 {
            get {
                return ResourceManager.GetString("StartingAtDay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Starting at hour 的當地語系化字串。
        /// </summary>
        public static string StartingAtHour {
            get {
                return ResourceManager.GetString("StartingAtHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Every 的當地語系化字串。
        /// </summary>
        public static string StartingAtHour2 {
            get {
                return ResourceManager.GetString("StartingAtHour2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Starting at minute 的當地語系化字串。
        /// </summary>
        public static string StartingAtMinute {
            get {
                return ResourceManager.GetString("StartingAtMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Every 的當地語系化字串。
        /// </summary>
        public static string StartingAtMinute2 {
            get {
                return ResourceManager.GetString("StartingAtMinute2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Starting on the 的當地語系化字串。
        /// </summary>
        public static string StartingAtMonth {
            get {
                return ResourceManager.GetString("StartingAtMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Every 的當地語系化字串。
        /// </summary>
        public static string StartingAtMontn2 {
            get {
                return ResourceManager.GetString("StartingAtMontn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 StopAgent 的當地語系化字串。
        /// </summary>
        public static string StopBackgroudJobButtonName {
            get {
                return ResourceManager.GetString("StopBackgroudJobButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Submit 的當地語系化字串。
        /// </summary>
        public static string SubmitButtonName {
            get {
                return ResourceManager.GetString("SubmitButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Weekday 的當地語系化字串。
        /// </summary>
        public static string Weekday {
            get {
                return ResourceManager.GetString("Weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Starting on the 的當地語系化字串。
        /// </summary>
        public static string WeekDay1 {
            get {
                return ResourceManager.GetString("WeekDay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 st weekday  Specific day of  的當地語系化字串。
        /// </summary>
        public static string WeekDay12 {
            get {
                return ResourceManager.GetString("WeekDay12", resourceCulture);
            }
        }
    }
}
