//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.HttpJob.Content.resx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hangfire.HttpJob.Content.resx.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 CronGenerator 的本地化字符串。
        /// </summary>
        public static string AddCronButtonName {
            get {
                return ResourceManager.GetString("AddCronButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddDelayJob 的本地化字符串。
        /// </summary>
        public static string AddHttpJobButtonName {
            get {
                return ResourceManager.GetString("AddHttpJobButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddRecurringJob 的本地化字符串。
        /// </summary>
        public static string AddRecurringJobHttpJobButtonName {
            get {
                return ResourceManager.GetString("AddRecurringJobHttpJobButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string CloseButtonName {
            get {
                return ResourceManager.GetString("CloseButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JobWS 的本地化字符串。
        /// </summary>
        public static string DashboardName {
            get {
                return ResourceManager.GetString("DashboardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JobManager 的本地化字符串。
        /// </summary>
        public static string DashboardTitle {
            get {
                return ResourceManager.GetString("DashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EditRecurringJob 的本地化字符串。
        /// </summary>
        public static string EditRecurringJobButtonName {
            get {
                return ResourceManager.GetString("EditRecurringJobButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JobName 的本地化字符串。
        /// </summary>
        public static string JobName {
            get {
                return ResourceManager.GetString("JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JobParam 的本地化字符串。
        /// </summary>
        public static string JobParam {
            get {
                return ResourceManager.GetString("JobParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JobResult 的本地化字符串。
        /// </summary>
        public static string JobResult {
            get {
                return ResourceManager.GetString("JobResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job Start Time 的本地化字符串。
        /// </summary>
        public static string JobStart {
            get {
                return ResourceManager.GetString("JobStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string LogOutButtonName {
            get {
                return ResourceManager.GetString("LogOutButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause | Start 的本地化字符串。
        /// </summary>
        public static string PauseJobButtonName {
            get {
                return ResourceManager.GetString("PauseJobButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QueuenName 的本地化字符串。
        /// </summary>
        public static string QueuenName {
            get {
                return ResourceManager.GetString("QueuenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HttpStatusCode 的本地化字符串。
        /// </summary>
        public static string ResponseCode {
            get {
                return ResourceManager.GetString("ResponseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pelese Enter JobName Or Args ... 的本地化字符串。
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        public static string SubmitButtonName {
            get {
                return ResourceManager.GetString("SubmitButtonName", resourceCulture);
            }
        }
    }
}
