#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.HttpJob.Dashboard.Pages
{
    using System;
    
    #line 2 "..\..\Dashboard\Pages\CornJobsPage.cshtml"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Dashboard\Pages\CornJobsPage.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\Dashboard\Pages\CornJobsPage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Dashboard\Pages\CornJobsPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Dashboard\Pages\CornJobsPage.cshtml"
    using Hangfire.Dashboard.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class CornJobsPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");








            
            #line 8 "..\..\Dashboard\Pages\CornJobsPage.cshtml"
  
    Layout = new LayoutPage(Hangfire.HttpJob.Content.resx.Strings.AddCronButtonName);


            
            #line default
            #line hidden
WriteLiteral(@"
<style>
    body {
        width: 50%;
        margin: 0 auto;
        padding-bottom: 20px;
    }

    input[type=number] {
        height: 25px;
        width: 52px;
    }

    .search-field input[type=text] {
        width: 152px !important;
    }
</style>
<div>
    <div style=""text-align: center;"">
        <h3>");


            
            #line 30 "..\..\Dashboard\Pages\CornJobsPage.cshtml"
       Write(Hangfire.HttpJob.Content.resx.Strings.AddCronButtonName);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n        <br>\r\n    </div>\r\n    <div>\r\n        <!-- Nav tabs -->\r\n        <u" +
"l class=\"nav nav-tabs\" role=\"tablist\">\r\n            ");



WriteLiteral(@"
            <li role=""presentation"" class=""active"">
                <a href=""#minute"" aria-controls=""minute"" role=""tab"" data-toggle=""tab"">分钟</a>
            </li>
            <li role=""presentation"">
                <a href=""#hour"" aria-controls=""hour"" role=""tab"" data-toggle=""tab"">小时</a>
            </li>
            <li role=""presentation"">
                <a href=""#day"" aria-controls=""day"" role=""tab"" data-toggle=""tab"">日</a>
            </li>
            <li role=""presentation"">
                <a href=""#month"" aria-controls=""month"" role=""tab"" data-toggle=""tab"">月</a>
            </li>
            <li role=""presentation"">
                <a href=""#week"" aria-controls=""week"" role=""tab"" data-toggle=""tab"">周</a>
            </li>
            ");



WriteLiteral("\r\n        </ul>\r\n\r\n        <!-- Tab panes -->\r\n        <div class=\"tab-content\">\r" +
"\n\r\n            <!--秒-->\r\n            ");



WriteLiteral("\r\n\r\n            <!--分钟-->\r\n            <div role=\"tabpanel\" class=\"tab-pane activ" +
"e\" id=\"minute\">\r\n                <div class=\"radio\">\r\n                    <label" +
">\r\n                        <input type=\"radio\" name=\"minuteType\" value=\"All\" che" +
"cked=\"checked\">\r\n                        每分钟 允许的通配符[, - * /]\r\n                  " +
"  </label>\r\n                </div>\r\n                <div class=\"radio\">\r\n       " +
"             <label>\r\n                        <input type=\"radio\" name=\"minuteTy" +
"pe\" value=\"Cyclic\">\r\n                        周期从\r\n                        <input" +
" type=\"number\" id=\"minuteTypeCyclic_1\" value=\"\">\r\n                        -\r\n   " +
"                     <input type=\"number\" id=\"minuteTypeCyclic_2\" value=\"\">\r\n   " +
"                     分钟\r\n                    </label>\r\n                </div>\r\n\r" +
"\n                <div class=\"radio\">\r\n                    <label>\r\n             " +
"           <input type=\"radio\" name=\"minuteType\" value=\"Interval\">\r\n            " +
"            从\r\n                        <input type=\"number\" id=\"minuteTypeInterv" +
"al_1\" value=\"\">\r\n                        分钟开始,每\r\n                        <input " +
"type=\"number\" id=\"minuteTypeInterval_2\" value=\"\">\r\n                        分钟执行一" +
"次\r\n                    </label>\r\n                </div>\r\n\r\n                <div " +
"class=\"radio\">\r\n                    <label>\r\n                        <input type" +
"=\"radio\" name=\"minuteType\" value=\"Assigned\">\r\n                        指定\r\n      " +
"              </label>\r\n                </div>\r\n                <div style=\"marg" +
"in-left: 20px;\">\r\n                    <select id=\"minuteTypeAssigned_1\" data-pla" +
"ceholder=\"选择指定的分钟...\"\r\n                            style=\"width:350px;\" multiple" +
"></select>\r\n                </div>\r\n            </div>\r\n\r\n            <!--小时-->\r" +
"\n            <div role=\"tabpanel\" class=\"tab-pane\" id=\"hour\">\r\n\r\n               " +
" <div class=\"radio\">\r\n                    <label>\r\n                        <inpu" +
"t type=\"radio\" name=\"hourType\" value=\"All\" checked=\"checked\">\r\n                 " +
"       每小时 允许的通配符[, - * /]\r\n                    </label>\r\n                </div>" +
"\r\n                <div class=\"radio\">\r\n                    <label>\r\n            " +
"            <input type=\"radio\" name=\"hourType\" value=\"Cyclic\">\r\n               " +
"         周期从\r\n                        <input type=\"number\" id=\"hourTypeCyclic_1\"" +
" value=\"\">\r\n                        -\r\n                        <input type=\"numb" +
"er\" id=\"hourTypeCyclic_2\" value=\"\">\r\n                        小时\r\n               " +
"     </label>\r\n                </div>\r\n\r\n                <div class=\"radio\">\r\n  " +
"                  <label>\r\n                        <input type=\"radio\" name=\"hou" +
"rType\" value=\"Interval\">\r\n                        从\r\n                        <in" +
"put type=\"number\" id=\"hourTypeInterval_1\" value=\"\">\r\n                        时开始" +
",每\r\n                        <input type=\"number\" id=\"hourTypeInterval_2\" value=\"" +
"\">\r\n                        小时执行一次\r\n                    </label>\r\n              " +
"  </div>\r\n\r\n                <div class=\"radio\">\r\n                    <label>\r\n  " +
"                      <input type=\"radio\" name=\"hourType\" value=\"Assigned\">\r\n   " +
"                     指定\r\n                    </label>\r\n                </div>\r\n " +
"               <div style=\"margin-left: 20px;\">\r\n                    <select id=" +
"\"hourTypeAssigned_1\" data-placeholder=\"选择指定的小时...\"\r\n                            " +
"style=\"width:350px;\" multiple></select>\r\n                </div>\r\n\r\n            <" +
"/div>\r\n\r\n\r\n            <!--日-->\r\n            <div role=\"tabpanel\" class=\"tab-pan" +
"e\" id=\"day\">\r\n\r\n                <div class=\"radio\">\r\n                    <label>" +
"\r\n                        <input type=\"radio\" name=\"dayType\" value=\"All\" checked" +
"=\"checked\">\r\n                        每日 允许的通配符[, - * / L W]\r\n                   " +
" </label>\r\n                </div>\r\n                <div class=\"radio\">\r\n        " +
"            <label>\r\n                        <input type=\"radio\" name=\"dayType\" " +
"value=\"Cyclic\">\r\n                        周期从\r\n                        <input typ" +
"e=\"number\" id=\"dayTypeCyclic_1\" value=\"\">\r\n                        -\r\n          " +
"              <input type=\"number\" id=\"dayTypeCyclic_2\" value=\"\">\r\n             " +
"           日\r\n                    </label>\r\n                </div>\r\n\r\n          " +
"      <div class=\"radio\">\r\n                    <label>\r\n                        " +
"<input type=\"radio\" name=\"dayType\" value=\"Interval\">\r\n                        从\r" +
"\n                        <input type=\"number\" id=\"dayTypeInterval_1\" value=\"\">\r\n" +
"                        日开始,每\r\n                        <input type=\"number\" id=\"" +
"dayTypeInterval_2\" value=\"\">\r\n                        日执行一次\r\n                   " +
" </label>\r\n                </div>\r\n\r\n                <div class=\"radio\">\r\n      " +
"              <label>\r\n                        <input type=\"radio\" name=\"dayType" +
"\" value=\"Assigned\">\r\n                        指定\r\n                    </label>\r\n " +
"               </div>\r\n                <div style=\"margin-left: 20px;\">\r\n       " +
"             <select id=\"dayTypeAssigned_1\" data-placeholder=\"选择指定的日...\"\r\n      " +
"                      style=\"width:350px;\" multiple></select>\r\n                <" +
"/div>\r\n\r\n                <div class=\"radio\">\r\n                    <label>\r\n     " +
"                   <input type=\"radio\" name=\"dayType\" value=\"NotAssigned\">\r\n    " +
"                    不指定\r\n                    </label>\r\n                </div>\r\n\r" +
"\n                <div class=\"radio\">\r\n                    <label>\r\n             " +
"           <input type=\"radio\" name=\"dayType\" value=\"RecentDays\">\r\n             " +
"           每月\r\n                        <input type=\"number\" id=\"dayTypeRecentDay" +
"s_1\" value=\"\">\r\n                        号最近的那个工作日\r\n                    </label>\r" +
"\n                </div>\r\n                <div class=\"radio\">\r\n                  " +
"  <label>\r\n                        <input type=\"radio\" name=\"dayType\" value=\"Las" +
"tDayOfMonth\">\r\n                        本月最后一天\r\n                    </label>\r\n   " +
"             </div>\r\n                <div class=\"radio\">\r\n                    <l" +
"abel>\r\n                        <input type=\"radio\" name=\"dayType\" value=\"LastDay" +
"OfMonthRecentDays\">\r\n                        本月最后一个工作日\r\n                    </la" +
"bel>\r\n                </div>\r\n            </div>\r\n\r\n\r\n            <!--月-->\r\n    " +
"        <div role=\"tabpanel\" class=\"tab-pane\" id=\"month\">\r\n                <div " +
"class=\"radio\">\r\n                    <label>\r\n                        <input type" +
"=\"radio\" name=\"monthType\" value=\"All\" checked=\"checked\">\r\n                      " +
"  每月 允许的通配符[, - * /]\r\n                    </label>\r\n                </div>\r\n    " +
"            <div class=\"radio\">\r\n                    <label>\r\n                  " +
"      <input type=\"radio\" name=\"monthType\" value=\"Cyclic\">\r\n                    " +
"    周期从\r\n                        <input type=\"number\" id=\"monthTypeCyclic_1\" val" +
"ue=\"\">\r\n                        -\r\n                        <input type=\"number\" " +
"id=\"monthTypeCyclic_2\" value=\"\">\r\n                        月\r\n                   " +
" </label>\r\n                </div>\r\n\r\n                <div class=\"radio\">\r\n      " +
"              <label>\r\n                        <input type=\"radio\" name=\"monthTy" +
"pe\" value=\"Interval\">\r\n                        从\r\n                        <input" +
" type=\"number\" id=\"monthTypeInterval_1\" value=\"\">\r\n                        月开始,每" +
"\r\n                        <input type=\"number\" id=\"monthTypeInterval_2\" value=\"\"" +
">\r\n                        月执行一次\r\n                    </label>\r\n                " +
"</div>\r\n\r\n                <div class=\"radio\">\r\n                    <label>\r\n    " +
"                    <input type=\"radio\" name=\"monthType\" value=\"Assigned\">\r\n    " +
"                    指定\r\n                    </label>\r\n                </div>\r\n  " +
"              <div style=\"margin-left: 20px;\">\r\n                    <select id=\"" +
"monthTypeAssigned_1\" data-placeholder=\"选择指定的月...\"\r\n                            s" +
"tyle=\"width:350px;\" multiple></select>\r\n                </div>\r\n\r\n              " +
"  ");



WriteLiteral("\r\n            </div>\r\n\r\n\r\n            <!--周-->\r\n            <div role=\"tabpanel\" " +
"class=\"tab-pane\" id=\"week\">\r\n                <div class=\"radio\">\r\n              " +
"      <label>\r\n                        <input type=\"radio\" name=\"weekType\" value" +
"=\"All\" checked=\"checked\">\r\n                        每周 允许的通配符[, - * / L #]\r\n     " +
"               </label>\r\n                </div>\r\n                <div class=\"rad" +
"io\">\r\n                    <label>\r\n                        <input type=\"radio\" n" +
"ame=\"weekType\" value=\"Cyclic\">\r\n                        周期从\r\n                   " +
"     <input type=\"number\" id=\"weekTypeCyclic_1\" value=\"\">\r\n                     " +
"   -\r\n                        <input type=\"number\" id=\"weekTypeCyclic_2\" value=\"" +
"\">\r\n                        周\r\n                    </label>\r\n                </d" +
"iv>\r\n\r\n                <div class=\"radio\">\r\n                    <label>\r\n       " +
"                 <input type=\"radio\" name=\"weekType\" value=\"WeeksOfWeek\">\r\n     " +
"                   第\r\n                        <input type=\"number\" id=\"weekTypeW" +
"eeksOfWeek_1\" value=\"\">\r\n                        周 的星期\r\n                        " +
"<input type=\"number\" id=\"weekTypeWeeksOfWeek_2\" value=\"\">\r\n\r\n                   " +
" </label>\r\n                </div>\r\n\r\n                <div class=\"radio\">\r\n      " +
"              <label>\r\n                        <input type=\"radio\" name=\"weekTyp" +
"e\" value=\"Assigned\">\r\n                        指定\r\n                    </label>\r\n" +
"                </div>\r\n                <div style=\"margin-left: 20px;\">\r\n      " +
"              <select id=\"weekTypeAssigned_1\" data-placeholder=\"选择指定的周...\"\r\n    " +
"                        style=\"width:350px;\" multiple></select>\r\n               " +
" </div>\r\n\r\n                <div class=\"radio\">\r\n                    <label>\r\n   " +
"                     <input type=\"radio\" name=\"weekType\" value=\"NotAssigned\">\r\n " +
"                       不指定\r\n                    </label>\r\n                </div>" +
"\r\n                <div class=\"radio\">\r\n                    <label>\r\n            " +
"            <input type=\"radio\" name=\"weekType\" value=\"LastWeekOfMonth\">\r\n      " +
"                  本月最后一个星期\r\n                        <input type=\"number\" id=\"wee" +
"kTypeLastWeekOfMonth_1\" value=\"1\">\r\n\r\n                    </label>\r\n            " +
"    </div>\r\n            </div>\r\n\r\n\r\n            <!--年-->\r\n            ");



WriteLiteral(@"

        </div>
    </div>
    <hr>

    <div class=""panel panel-info"">
        <div class=""panel-heading"">
            <h3 class=""panel-title"">结果</h3>
        </div>

        <div class=""panel-body"">

            <form class=""form-inline"">
                <!--<div class=""form-group"">
                    <label class=""sr-only"">结果</label>
                    <p class=""form-control-static"">结果</p>
                </div>-->
                <div class=""form-group"">
                    <label for=""result"" class=""sr-only"">Password</label>
                    <input type=""text"" class=""form-control"" style=""width: 500px;"" id=""result"" placeholder=""结果"">
                </div>
                <button type=""button"" id=""analysis"" class=""btn btn-default"">反解析</button>
            </form>
        </div>
    </div>
</div>");


        }
    }
}
#pragma warning restore 1591
